### ISSUE TITLE
Is it possible to get the list of  [model selector] & [diff pin]?

### ISSUE THREAD

**Issue by SHF101202021** [eerimoq/ecdtools#1]
# Is it possible to get the list of  [model selector]?

Hi, I'm Szuhsien. 
Due to needs of jobs, the analysis of IBIS file is needed.
Luckily, I found your ***ecdtools*** helping me a lot.
However, I don't know how to extract the information of [model selector] & [diff pin]
Could you please give me a hand?
Thank you so much

PS. I saw your function Parser().grammer seeming to enable acquiring information for anything. But I don't know how to use it.

Szuhsien

**Comment by eerimoq** [comment]
Hi!

I'v actually never used this library myself and I have minimal experience from IBIS files. If you can provide a detailed description of what you need I might be able to help.

**Comment by SHF101202021** [comment]
Thanks for your kind replies!

To be simplest, can you explain the function of ***grammar*** and how to use it?

In your ***grammar*** function, it seems like that you can extract the information of [diff pin] & [model selector].
I want to know how to use this function in order to get the information I want.

> ***Copied from your kind source codes***
> class Parser(textparser.Parser):
>   ...
>   def grammar(self):
>     ...
>     model_selector = Sequence('[model selector]', 'WS', 'WORD',
                                  ZeroOrMore(Sequence(nls, 'WORD', any_until_nl)))
>     ...
>     diff_pin = Sequence('[diff pin]',
                            'WS', 'WORD',
                            'WS', 'WORD',
                            'WS', 'WORD',
                            'WS', 'WORD',
                            'WS', 'WORD',
                            ZeroOrMore(Sequence(nls, 'WORD',
                                                'WS', 'WORD',
                                                'WS', 'WORD',
                                                'WS', 'WORD',
                                                'WS', 'WORD',
                                                'WS', 'WORD')))
>     ...

The format of the model selector is like the following:
![model_selector](https://user-images.githubusercontent.com/88426850/128154143-ba9d52c7-b425-45c6-9798-48955d0c235e.PNG)

**Comment by eerimoq** [comment]
The grammar method is internal and not meant to be used by the user. We have to write some code to extract `[model selector]` and `[diff pin]` data and make it available to the user.

What should `<what should be printed?>` be replaced by below to be useful to you? Or is there a better way to access the data?

```python
>>> from pprint import pprint
>>> import ecdtools
>>> ibs_file = ecdtools.ibis.load_file('tests/files/ibis/pybis/bushold.ibs',
                                       transform=True)
>>> pprint(ibs_file.model_selector)
<what should be printed?>
>>> pprint(ibs_file.diff_pin)
<what should be printed?>
```

**Comment by eerimoq** [comment]
This works with the latest release (I just released it).

From ibs-file:

```
[Diff Pin] inv_pin vdiff tdelay_typ tdelay_min tdelay_max 
E17     D18     2.0         NA              NA              NA              
[Model Selector]    BUSB6AU
BUSB6AU_HIGH_SPEED       USB_HIGH_SPEED                    
BUSB6AU_LOW_SPEED        USB_LOW_SPEED                    
```

How to access the data:

```python
>>> from pprint import pprint
>>> import ecdtools
>>> ibs_file = ecdtools.ibis.load_file('workspace/ecdtools/tests/files/ibis/pybis/sample1.ibs')
>>> ibs_file.model_selector_names
['BUSB6AU']
>>> model_selector = ibs_file.get_model_selector_by_name('BUSB6AU')
>>> model_selector.name
'BUSB6AU'
>>> model_selector.models[0].name
'BUSB6AU_HIGH_SPEED'
>>> ibs_file.components[0].diff_pins[0].name
'E17'
>>> 
```

**Comment by SHF101202021** [comment]
Notice that ```[diff pin]``` & ```[model selector]``` are not necessary for an IBIS file. They could be **```None```**

### ```[Model Selector]```
![image](https://user-images.githubusercontent.com/88426850/128159072-afd4e6e7-2257-4aa1-aae9-7c2d53388498.png)
For ```ibs_file.model_selector```, I just use the ```dict``` to express my expectation (See above picture as examples):
```
ibs_file.model_selector = {"NC/SIO3":["NC/SIO3_24ohm ODS[2:0]=111", ..., "NC/SIO3_146ohm ODS[2:0]=000"],
                           "SO/SIO1":["SO/SIO1_24ohm ODS[2:0]=111", ..., "SO/SIO1_146ohm ODS[2:0]=000"], 
                           ...}                                                           
```
The string ```"NC/SIO3_24ohm"``` is **model name** with extra auxiliary descriptions, so if it is possible to let ```"NC/SIO3_24ohm ODS[2:0]=111"``` to refer to the model,```"NC/SIO3_24ohm"``` , that's better.

### ```[Diff Pin]```
![image](https://user-images.githubusercontent.com/88426850/128161480-5b9bbd93-29a3-4bde-b045-5ae20289fca7.png)
```
ibs_file.diff_pin = {"name": ["A17", ..., "W13"],
                    "inv_pin": ["A18:, ..., "Y13"], 
                    "vdiff": ["175m", ..., "NA"],
                    "tdelay_typ": ["NA", ..., "NA"], 
                    ...}
```
For typ, max, min, I think you can keep the class TypMinMax().

If there is any unclear thing, please tell me.
Thank you very much!

**Comment by eerimoq** [comment]
Let me know if you want me to change something! As I said, I have no experience of how to use IBIS files =)

**Comment by SHF101202021** [comment]
Wow, thanks so much !!!!!!
It really helps me a lot!

**Comment by SHF101202021** [comment]
Hi. Is it possible to retain the **description** of the model in ```[model selector]```?
Like this:
```
>>> model_selector.models[0].description
USB_HIGH_SPEED
>>> model_selector.models[1].description
USB_LOW_SPEED

```
---
Also, I have one feedback and one bug(? for your outstanding ***ecdtools package***:
###  Feedback: Tutorial for users
If possible, users need a simple guideline to get the important information of IBIS:
- IV curves of **Pullup**, **Pulldown**, **Power Clamp** and **GND Clamp**
- VT curves of **rising waveforms** and **falling waveforms**
- Information of Pa**ckage/Pin RLC** and **Component Capacitance**
- Details of the specified model (e.g. vinl, vinh, etc)

For pure python users like me, it took one day to search the information in your source code.
I thought users would like to see a guideline for those informations.

### Bug(? : Wrong loads for the following *FILE HEADER INFORMATION*
Wrong file header information:

```
[IBIS Ver] 3.2
[File Name] mx25u25645gmi.ibs
[File Rev] @(#)$Revision: 1.1 $
[Date] @(#)$Date: 2017/04/19 06:25:06 $
```

Error Message:
```
ParseError: Invalid syntax at line 3, column 26: "[File Rev] @(#)$Revision:>>!<< 1.1 $"
```

Normal file header information (I remove special letters):
```
[IBIS Ver] 3.2
[File Name] mx25u25645gmi.ibs
[File Rev] 1.1   
[Date] Date: 2017/04/19 06:25:06 
```

I don't know how the special letters interrupt your parsing. I just report it to you.
These special letters are given by the vendors, not user's filling

**Comment by eerimoq** [comment]
As I'm not familiar with how IBIS files are used I can't write such documentation. It would be lovely if you can write such documentation and submit it as a PR (pull request). I guess it should be added to docs/index.rst, or possibly the readme.

**Comment by SHF101202021** [comment]
Hi. I'm pleased to help you write such a file, but may be later. (I'm not familiar with PR, and I need to do some studies)

Besides the tutorial, how about your kind comments to 
1. the probable bug for **file header information** 
2. adding **descriptions** of the model in ```[model selector]``` just like your ```description``` in ```ModelSelectorModel```

Definition of ```Class ModelSelectorModel```:
```
class ModelSelectorModel(object):
    def __init__(self, name, description):
        self.name = name
        self.description = description

```

**Comment by eerimoq** [comment]
2. What is missing? Isn't the description already there?

**Comment by SHF101202021** [comment]
Oh. Please take my apology for misunderstanding for your coding.
I've found with the commands 
```
>>> ibs_file.model_selector[0].models[0].description
USB_HIGH_SPEED
```
Thanks!

**Comment by eerimoq** [comment]
I relaxed the header parsing to fix 1. Part of release 0.5.1, soon published to PyPI.

**Comment by SHF101202021** [comment]
It works!!
Thank you!!
